### ISSUE TITLE
Issue connecting Tableau to Elasticsearch

### ISSUE THREAD

**Issue by chloe-zh** [opendistro-for-elasticsearch/sql-odbc#123]
Original issue link: [Issue connecting Tableau to Elasticsearch #256](https://github.com/opendistro/for-elasticsearch-docs/issues/256)
Transfer this issue from doc repository for our user

**Comment by jordanw-bq** [comment]
@chloe-zh This issue can be closed if there is no follow-up; we've responded to the user at the issue you linked.
