### ISSUE TITLE
Cannot specify SSL certificate

### ISSUE THREAD

**Issue by johncwetzel** [opendistro-for-elasticsearch/sql-odbc#124]
I am unable to get a successful test when setting up the Elasticsearch ODBC Driver DSN Setup. I believe this is due to the inability to specify an SSL certificate for it to use. I do see under "Advanced Options" the check box to "Enable SSL". However, I am unsure of what certificate(s) the driver uses when it does this. I see the driver for the regular version of elasticsearch allows ssl certificate specification. Is there documentation on how i can specify a certificate, or is this an incoming feature?

Details:
I am using opendistro elasticsearch on linux vm. I have ssl enabled on the http port of my opendistro elasticsearch cluster. It uses my internal, self-signed certificate chain. On my windows vm, I am attempting to set up the ODBC Driver on my windows workstation. I specifiy the host, port, basic auth, user, password, and check the "Enable ssl" box in advanced options. When i click the "Test" button in the ODBC window, the odbc wndw returns "Failed to establish connection to DB". I can see in my elasticsearch logs an exception that includes "Exception during establishing a SSL connection:" and a long stack trace at the exact same time. I strongly suspect this is because the ODBC driver is not providing/trusting/verifying the right certificate for the ssl settings i have on the elasticsearch cluster. 

Thank you very much for your time and attention

**Comment by rupal-bq** [comment]
@johncwetzel Adding a certificate to the default trust store will most likely solve your problem. When you select Enable SSL in advanced options it sets a [scheme in AWS Client Configuration](https://github.com/opendistro-for-elasticsearch/sql-odbc/blob/23caa2075f3b35352e1d606a75a41070470ca52e/src/odfesqlodbc/es_communication.cpp#L248)

If you can send a request from Postman successfully with SSL certificate verification ON and without adding a certificate, then the driver response should be a success as well.

Currently, the driver doesn't support specifying the SSL certificate. Will look into it.

**Comment by johncwetzel** [comment]
Hmm, I have added the certificate to the windows certmgr trusted root certification authorities, and my test still fails. However, i cannot successfully send a request with postman either, so there may be more configuration that I need to do on my end. Thank you for your response
