### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by coderReview** [opendistro-for-elasticsearch/sql-odbc#94]
I cannot connect to server.

Server version: Opendistro 1.7.0
ODBC client version: 0.2.0

Error: Failed to Establish Connection to DB

Windows: Windows Server 2012R2

**Comment by coderReview** [comment]
Log:
```
mylog.c[InitializeLogging]531:  es_odbc.c[DllMain]111: dlg_specif[CC_conninfo_init]452:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145: dlg_specif[CC_conninfo_init]452: dlg_specif[getDSNinfo]224:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145:    setup.c[test_connection]431: odbcapi30.[SQLAllocHandle]33:  environ.c[ESAPI_AllocEnv]44:  environ.c[ESAPI_AllocEnv]60: odbcapi30.[SQLSetEnvAttr]431: odbcapi30.[SQLAllocHandle]33: connection[ESAPI_AllocConnect]63: connection[ESAPI_AllocConnect]66:  environ.c[EN_add_connection]502:  environ.c[EN_add_connection]531: odbcapiw.c[SQLDriverConnectW]122: win_unicod[ucs2_to_utf8]126:  newlen=215 olen=215 utf8str=DRIVER=elasticsearchodbc;server=hostname.hostname.biz;database=elasticsearch;port=9200;UID=admin;PWD=admin;auth=NONE;region=;useSSL=1;hostnameVerification=0;logLevel=5;logOutput=C:\;responseTimeout=10;fetchSize=0;
    misc.c[make_string]115:     misc.c[make_string]117: dlg_specif[CC_conninfo_init]452:  drvconn.c[dconn_get_attributes]223: dlg_specif[getDSNinfo]224:  drvconn.c[dconn_get_attributes]223: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]121: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145:    mylog.c[logs_on_off]234:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: connection[CC_set_error_statements]553: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: es_communi[ESCommunication::LogMsg]474: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: odbcapi30w[SQLGetDiagRecW]197: es_api30.c[ESAPI_GetDiagRec]39:  environ.c[ESAPI_ConnectError]228: connection[CC_get_error]618: connection[CC_get_error]630:  environ.c[ESAPI_ConnectError]245:  environ.c[ESAPI_ConnectError]332: es_api30.c[ESAPI_GetDiagRec]60: win_unicod[utf8_to_ucs2_lf]244:  string=elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB. ocount=92
odbcapi30.[SQLFreeHandle]219: connection[ESAPI_FreeConnect]207: connection[CC_Destructor]314: connection[CC_cleanup]413: connection[CC_set_error_statements]553: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: connection[CC_cleanup]428: dlg_specif[CC_conninfo_init]452: connection[CC_cleanup]494: connection[CC_Destructor]321: connection[CC_Destructor]332: connection[CC_Destructor]343: connection[ESAPI_FreeConnect]225: odbcapi30.[SQLFreeHandle]219:  environ.c[ESAPI_FreeEnv]69:  environ.c[EN_Destructor]442:  environ.c[EN_Destructor]465:  environ.c[EN_Destructor]477:  environ.c[ESAPI_FreeEnv]72:    setup.c[test_connection]431: odbcapi30.[SQLAllocHandle]33:  environ.c[ESAPI_AllocEnv]44:  environ.c[ESAPI_AllocEnv]60: odbcapi30.[SQLSetEnvAttr]431: odbcapi30.[SQLAllocHandle]33: connection[ESAPI_AllocConnect]63: connection[ESAPI_AllocConnect]66:  environ.c[EN_add_connection]502:  environ.c[EN_add_connection]531: odbcapiw.c[SQLDriverConnectW]122: win_unicod[ucs2_to_utf8]126:  newlen=216 olen=216 utf8str=DRIVER=elasticsearchodbc;server=hostname.hostname.biz;database=elasticsearch;port=9200;UID=admin;PWD=admin;auth=BASIC;region=;useSSL=1;hostnameVerification=0;logLevel=5;logOutput=C:\;responseTimeout=10;fetchSize=0;
    misc.c[make_string]115:     misc.c[make_string]117: dlg_specif[CC_conninfo_init]452:  drvconn.c[dconn_get_attributes]223: dlg_specif[getDSNinfo]224:  drvconn.c[dconn_get_attributes]223: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]121: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145:    mylog.c[logs_on_off]234:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: connection[CC_set_error_statements]553: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: es_communi[ESCommunication::LogMsg]474: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: odbcapi30w[SQLGetDiagRecW]197: es_api30.c[ESAPI_GetDiagRec]39:  environ.c[ESAPI_ConnectError]228: connection[CC_get_error]618: connection[CC_get_error]630:  environ.c[ESAPI_ConnectError]245:  environ.c[ESAPI_ConnectError]332: es_api30.c[ESAPI_GetDiagRec]60: win_unicod[utf8_to_ucs2_lf]244:  string=elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB. ocount=92
```

**Comment by abbashus** [comment]
@jordanw-bq @rupal-bq can you take a look.

**Comment by coderReview** [comment]
I will update the log. It's the wrong one. One minute.

**Comment by abbashus** [comment]
We don't support `Windows Server 2012R2` as of yet. The only supported version for Windows is `Windows 10`
https://github.com/opendistro-for-elasticsearch/sql-odbc#supported-versions

**Comment by coderReview** [comment]
does that make a big difference?

**Comment by coderReview** [comment]
If I compile from source, would it work?

**Comment by jordanw-bq** [comment]
@coderReview We have not had a chance to verify the driver with the Windows Server platforms so far. If you provide the updated logs, we might be able to help provide a direction forward.

Could you also tell us what application (name and bitness (32 or 64 bit)) is using the driver?

**Comment by coderReview** [comment]
Actually I was using ODBC admin tool test button.

This is the configuration.

![image](https://user-images.githubusercontent.com/5925442/82360502-e19ad980-99df-11ea-9f2f-2264500e7ce7.png)

**Comment by coderReview** [comment]
Error

![image](https://user-images.githubusercontent.com/5925442/82360595-ff683e80-99df-11ea-8aaf-d8f27385f466.png)

**Comment by coderReview** [comment]
Log:

```
   mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531:  es_odbc.c[DllMain]111:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145:  es_odbc.c[DllMain]118:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531:  es_odbc.c[DllMain]111:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145: dlg_specif[getDSNinfo]224:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145:  es_odbc.c[DllMain]118:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531:  es_odbc.c[DllMain]111:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145: dlg_specif[getDSNinfo]224:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145:    setup.c[test_connection]431: connection[ESAPI_AllocConnect]66:  environ.c[EN_add_connection]531: win_unicod[ucs2_to_utf8]126:  newlen=216 olen=216 utf8str=DRIVER=elasticsearchodbc;server=hostname.hostname.biz;database=elasticsearch;port=9200;UID=admin;PWD=admin;auth=BASIC;region=;useSSL=1;hostnameVerification=0;logLevel=7;logOutput=C:\;responseTimeout=10;fetchSize=0;
    misc.c[make_string]115:     misc.c[make_string]117:  drvconn.c[dconn_get_attributes]223: dlg_specif[getDSNinfo]224:  drvconn.c[dconn_get_attributes]223: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]121: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145: dlg_specif[copyConnAttributes]145:    mylog.c[logs_on_off]234:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: es_communi[ESCommunication::LogMsg]474: connection[CC_set_error_statements]553: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: es_communi[ESCommunication::LogMsg]474: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: odbcapi30w[SQLGetDiagRecW]197: es_api30.c[ESAPI_GetDiagRec]39:  environ.c[ESAPI_ConnectError]228: connection[CC_get_error]618: connection[CC_get_error]630:  environ.c[ESAPI_ConnectError]245:  environ.c[ESAPI_ConnectError]332: es_api30.c[ESAPI_GetDiagRec]60: win_unicod[utf8_to_ucs2_lf]244:  string=elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB. ocount=92
odbcapi30.[SQLFreeHandle]219: connection[ESAPI_FreeConnect]207: connection[CC_Destructor]314: connection[CC_cleanup]413: connection[CC_set_error_statements]553: connection[CC_log_error]641: connection[CC_log_error]644: connection[CC_log_error]647: connection[CC_log_error]650: connection[CC_cleanup]428: dlg_specif[CC_conninfo_init]452: connection[CC_cleanup]494: connection[CC_Destructor]321: connection[CC_Destructor]332: connection[CC_Destructor]343: connection[ESAPI_FreeConnect]225: odbcapi30.[SQLFreeHandle]219:  environ.c[ESAPI_FreeEnv]69:  environ.c[EN_Destructor]442:  environ.c[EN_Destructor]465:  environ.c[EN_Destructor]477:  environ.c[ESAPI_FreeEnv]72:  es_odbc.c[DllMain]118:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531:  es_odbc.c[DllMain]111:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145: dlg_specif[getDSNinfo]224:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145:  es_odbc.c[DllMain]118:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531:  es_odbc.c[DllMain]111: dlg_specif[getDSNinfo]224:  es_odbc.c[DllMain]118:    mylog.c[logs_on_off]234: 	start_logging:Global.debug&commlog=5&5
   mylog.c[InitializeLogging]531:  es_odbc.c[DllMain]111:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145: dlg_specif[getDSNinfo]224:    setup.c[ParseAttributes]575: dlg_specif[copyConnAttributes]145:  es_odbc.c[DllMain]118: 
```

**Comment by coderReview** [comment]
I would like to use this with Power BI. Any hints on how to configure would help as well

**Comment by coderReview** [comment]
Server response from Postman

```JSON
{
  "name": "hostname",
  "cluster_name": "cluster",
  "cluster_uuid": "O7PI9F64QQSWIKmAYDUw8g",
  "version": {
    "number": "7.6.1",
    "build_flavor": "oss",
    "build_type": "rpm",
    "build_hash": "aa751e09be0a5072e8570670309b1f12348f023b",
    "build_date": "2020-02-29T00:15:25.529771Z",
    "build_snapshot": false,
    "lucene_version": "8.4.0",
    "minimum_wire_compatibility_version": "6.8.0",
    "minimum_index_compatibility_version": "6.0.0-beta1"
  },
  "tagline": "You Know, for Search"
}
```

**Comment by coderReview** [comment]
@jordanw-bq let me know if you need more information

**Comment by nikersason** [comment]
I am seeing the same behavior, but on Windows 10

**Comment by jordanw-bq** [comment]
@coderReview @nikersason Is the OpenDistro SQL Plugin installed on your server? The ODBC driver requires this in order to execute SQL queries against your OpenDistro data.

You can check this using the [CAT API](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/catapis/).
https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/catapis/#plugins

**Comment by coderReview** [comment]
hi @jordanw-bq all plugins, including SQL, are installed. I've done it using YUM command.

**Comment by nikersason** [comment]
@jordanw-bq I also confirmed using the cat api that I have the opendistro_sql v1.7.0.0 component installed. I spun up a local Open Distro for Elasticsearch Docker instance to try to narrow down the issue and can't connect to that (same error). Thank you for looking into this, and let me know if you have any other troubleshooting advice or need more information.

**Comment by jordanw-bq** [comment]
@coderReview @nikersason It looks like the installer included as part of the 1.7.0.0 GitHub release is incorrect, since the driver and installer files are showing a pre-release version (0.2.0). We will investigate the cause of this and update you when the proper installers are available.

**Comment by jordanw-bq** [comment]
@coderReview @nikersason We have updated the installer packages, which should now install the correct version of the driver. Can you uninstall your current version of the driver, and try the updated installers?
https://github.com/opendistro-for-elasticsearch/sql-odbc/releases/tag/v1.7.0.0

**Comment by nikersason** [comment]
@jordanw-bq - I've uninstalled the old version and installed 1.7, and unfortunately am seeing the same results. Any other ideas or things I should look at?

@coderReview - Have you had success?

**Comment by nikersason** [comment]
@jordanw-bq - I am seeing the following in my Elasticsearch logs at the time of connection attempts:
```
Exception during establishing a SSL connection: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record
```
I've tried testing this from Windows ODBC Data Source Administrator (checking the Enable SSL option), and on MacOS through iODBC Administrator as well as iodbctest on the command line with a connection string that includes UseSSL=1. Have tried these with and without HostnameVerification. 

Any ideas based on this information?

**Comment by coderReview** [comment]
Having the same problem as well @nikersason @jordanw-bq

**Comment by rupal-bq** [comment]
@coderReview When you tested the Server response from Postman, What URL did you use?

**Comment by coderReview** [comment]
hello @rupal-bq, I've used https://hostname:9200/

hostname => my server's name

**Comment by coderReview** [comment]
Also, I am using Self-Signed certificates.

**Comment by rupal-bq** [comment]
@coderReview Can you try setting DSN with host => https://hostname, port =>9200. I think there might be a problem with the SSL config.

**Comment by jzhou3** [comment]
> @abbashus, Would you please create a Window version of installer for 1.8 version of odbc drivier?

**Comment by abbashus** [comment]
@jzhou3 You can download from [here](https://github.com/opendistro-for-elasticsearch/sql-odbc/actions/runs/109014247)

**Comment by jzhou3** [comment]
@abbashus Thank you for sharing the installer file. Our AWS authentication is AWS Signed V4 using KeyID and SecretKey.  I created the aws-auth connection property credentials files under C:\Users\[user name]\.aws based on reading on (https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/credentials.html),  I am getting the error: "elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB."  Any suggestions?

**Comment by jordanw-bq** [comment]
@jzhou3 Our documentation will be updated to include this note, but the credentials for AWS authentication with ODFE need to be in a specific profile in your credentials file, named `elasticsearchodbc`.

Example `.aws/credentials` file:
```
[default]
aws_access_key_id = xxx
aws_secret_access_key = xxx

[elasticsearchodbc]
aws_access_key_id=<ODFE KeyID>
aws_secret_access_key=<ODFE SecretKey>
```

**Comment by nikersason** [comment]
@rupal-bq I have tried setting DSN with host => https://hostname, port =>9200 as you suggested to @coderReview , with no success. I no longer see "not an SSL/TLS record" in my ES logs but still get "Failed to establish connection" in my ODBC logs. Have you been able to connect successfully over SSL?

**Comment by coderReview** [comment]
@nikersason I will try today as well.

**Comment by coderReview** [comment]
@rupal-bq using https didn't work. Without https I am getting the same exception as @nikersason.

**Comment by coderReview** [comment]
do you have a working example to provide?

**Comment by rupal-bq** [comment]
@coderReview @nikersason I am not to reproduce the issue. Can you use the installer (https://github.com/opendistro-for-elasticsearch/sql-odbc/actions/runs/122823780) and set the log level to LOG_ALL and share logs. This will add more information in logs.

Also, please share the steps you followed to setup the server and use the driver, it would help to reproduce the issue.

**Comment by coderReview** [comment]
@rupal-bq same problem. I am using a Self Signed Certificate. Can that cause any issue?

**Comment by coderReview** [comment]
I will share logs ASAP.

**Comment by coderReview** [comment]
It tries to connect to a database called `elasticsearch`. What is that?

**Comment by rupal-bq** [comment]
that database option isn't getting used while connecting since elasticsearch server doesn't support multiple database/catalog. I am not entirely sure if Self Signed Certificate is causing any problem, logs will have a server response, which will help us identify the problem.

**Comment by nikersason** [comment]
In my case, I am trying an OpenDistro ElasticSearch Docker container using instructions here: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

![image](https://user-images.githubusercontent.com/4894574/83575153-8b0bc000-a4f4-11ea-95a7-f6367eae5fe1.png)
[mylog_odbcad32_25160.log](https://github.com/opendistro-for-elasticsearch/sql-odbc/files/4719977/mylog_odbcad32_25160.log)

I see an error in the logs indicating the SQL Plugin must be installed, but I confirmed opendistro_sql is installed using /_cat/plugins request.

I also still see `io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record` in my ElasticSearch logs.

**Comment by coderReview** [comment]
I am trying to get some info using SSLDUMP

**Comment by nikersason** [comment]
I tried connecting to an AWS ElasticSearch Service Endpoint and was successful now, provided I include https in the hostname.

I wonder if @coderReview is onto something with the self signed cert question.

**Comment by coderReview** [comment]
![image](https://user-images.githubusercontent.com/5925442/83577393-70444600-a50a-11ea-969f-7b4f99032c45.png)

There is no SSL handshaking happening here. @nikersason are you using Self Signed certificates as well?

**Comment by nikersason** [comment]
@coderReview - looks like we commented at the same time. I was able to connect successfully to an AWS endpoint. Indeed my local instance is using self-signed certificates

**Comment by rupal-bq** [comment]
@coderReview @nikersason Thanks for sharing all information. I was able to reproduce the issue with it.

**Comment by jzhou3** [comment]
@rupal-bq for the tableau connection readme section, it says "Make sure the .tdc is copied to <user_home_directory>/Documents/My Tableau Repository/Datasources in both macOS and Windows." i only seeing a .tcd file in the source folder. Is that a typo? tcd vs. tdc

**Comment by rupal-bq** [comment]
@jzhou3 It isn't a typo. The `.tcd` file is part of the tableau connector and the `.tdc` file you want here is the one available in your resources folder after installation. https://github.com/opendistro-for-elasticsearch/sql-odbc/blob/master/src/installer/Resources/odfe_sql_odbc.tdc

**Comment by rupal-bq** [comment]
@coderReview @nikersason Disabling HostnameVerification isn't working on windows currently(https://github.com/aws/aws-sdk-cpp/pull/492). As the demo certs are not in the trust store, SSL certificate verification is failing.

We are working on a solution. Meanwhile, if you want to use SSL on windows, add certificates to the trust store.

Also if you are using SSL, you need to add https in the host. (eg. https://localhost)

**Comment by coderReview** [comment]
@rupal-bq added certificate to host but still got error:

```
dlg_specif[copyConnAttributes]145: key='DRIVER' value='elasticsearchodbc'
dlg_specif[copyConnAttributes]145: key='server' value='https://HOSTNAME'
dlg_specif[copyConnAttributes]145: key='database' value='elasticsearch' not found
dlg_specif[copyConnAttributes]145: key='port' value='9200'
dlg_specif[copyConnAttributes]145: key='UID' value='admin'
dlg_specif[copyConnAttributes]121: key='PWD' value='xxxxxxxx'
dlg_specif[copyConnAttributes]145: key='auth' value='BASIC'
dlg_specif[copyConnAttributes]145: key='region' value=''
dlg_specif[copyConnAttributes]145: key='useSSL' value='1'
dlg_specif[copyConnAttributes]145: key='hostnameVerification' value='1'
dlg_specif[copyConnAttributes]145: key='logLevel' value='7'
dlg_specif[copyConnAttributes]145: key='logOutput' value='C:\'
dlg_specif[copyConnAttributes]145: key='responseTimeout' value='10'
dlg_specif[copyConnAttributes]145: key='fetchSize' value='-1'
   mylog.c[logs_on_off]234: mylog_on=7 qlog_on=7
   mylog.c[logs_on_off]234: mylog_on=7 qlog_on=7
	start_logging:Global.debug&commlog=7&7
   mylog.c[InitializeLogging]531: Log Output Dir: C:\
es_communi[ESCommunication::LogMsg]571: Initializing Aws API.
es_communi[ESCommunication::LogMsg]571: Verifying connection options.
es_communi[ESCommunication::LogMsg]571: Required connection option are valid.
es_communi[ESCommunication::LogMsg]571: Starting DB connection.
es_communi[ESCommunication::LogMsg]571: Attempting to establish DB connection.
es_communi[ESCommunication::LogMsg]571: Checking for SQL plugin
es_communi[ESCommunication::LogMsg]571: The SQL plugin must be installed in order to use this driver. Client error: 'Encountered network error when sending http request'.
es_communi[ESCommunication::LogMsg]571: Failed to establish connection to DB.
es_communi[ESCommunication::LogMsg]571: Dropping DB connection.
connection[CC_set_error_statements]553: entering self=00000001127F9250
connection[CC_log_error]641: CONN ERROR: func=LIBES_connect, desc='', errnum=202, errmsg='elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB.'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=00000001127D7130, conn=00000001127F9250, status=0, num_stmts=16
connection[CC_log_error]650:             esconn=0000000000000000, stmts=00000001127FAD50, lobj_type=-999
es_communi[ESCommunication::LogMsg]571: Shutting down Aws API.
connection[CC_log_error]641: CONN ERROR: func=ESAPI_DriverConnect, desc='Error from CC_Connect', errnum=202, errmsg='elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB.'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=00000001127D7130, conn=00000001127F9250, status=0, num_stmts=16
connection[CC_log_error]650:             esconn=0000000000000000, stmts=00000001127FAD50, lobj_type=-999
odbcapi30w[SQLGetDiagRecW]197: entering
es_api30.c[ESAPI_GetDiagRec]39: entering type=2 rec=1
 environ.c[ESAPI_ConnectError]228: entering hdbc=00000001127F9250 <512>
connection[CC_get_error]618: entering
connection[CC_get_error]630: leaving
 environ.c[ESAPI_ConnectError]245: CC_get_error: status = 202, msg = #elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB.#
 environ.c[ESAPI_ConnectError]332: 	     szSqlState = '08001',len=92, szError='elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB.'
es_api30.c[ESAPI_GetDiagRec]60: leaving 0
win_unicod[utf8_to_ucs2_lf]244: ilen=92 bufcount=512 string=elasticsearch connection status was not CONNECTION_OK: Failed to establish connection to DB. ocount=92
odbcapi30.[SQLFreeHandle]219: entering
connection[ESAPI_FreeConnect]207: entering...hdbc=00000001127F9250
connection[CC_Destructor]314: entering self=00000001127F9250
connection[CC_cleanup]413: entering self=00000001127F9250
connection[CC_set_error_statements]553: entering self=00000001127F9250
connection[CC_log_error]641: CONN ERROR: func=CC_cleanup, desc='', errnum=1, errmsg='Connection not open'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=00000001127D7130, conn=00000001127F9250, status=0, num_stmts=16
connection[CC_log_error]650:             esconn=0000000000000000, stmts=00000001127FAD50, lobj_type=-999
connection[CC_cleanup]428: after LIBES_disconnect
dlg_specif[CC_conninfo_init]452: entering opt=1
connection[CC_cleanup]494: leaving
connection[CC_Destructor]321: after CC_Cleanup
connection[CC_Destructor]332: after free statement holders
connection[CC_Destructor]343: leaving
connection[ESAPI_FreeConnect]225: leaving...
odbcapi30.[SQLFreeHandle]219: entering
 environ.c[ESAPI_FreeEnv]69: entering env=00000001127D7130
 environ.c[EN_Destructor]442: entering self=00000001127D7130
 environ.c[EN_Destructor]465: clearing conns count=128
 environ.c[EN_Destructor]477: leaving rv=1
 environ.c[ESAPI_FreeEnv]72:    ok
 es_odbc.c[DllMain]118: DETACHING odfesqlodbc.dll

```

**Comment by rupal-bq** [comment]
@coderReview  Are you able to send a request from Postman successfully with SSL certificate verification ON and without adding a certificate? 

Currently, Disabling hostname verification isn't working on windows which is equivalent to SSL certificate verification in Postman so it will be ON by default. Also, we can't specify a certificate while connecting to Elasticsearch yet.

**Comment by coderReview** [comment]
Hi @rupal-bq does postman use the windows certificate manager? The same for the AWS library. I've added the self signed certificates to the windows trust store.

**Comment by coderReview** [comment]
I will try tomorrow

**Comment by vincent2mots** [comment]
Hello,

it seems I have the same issue there with :
 - Opendistro 1.9
 - Windows 10 odbc driver (64 bit)
 - The exact same error message @coderReview 

@rupal-bq : hello, you talked earlier about a GET Postman request to try. Can you please tell me which request you want to try?

Best regards,

**Comment by rupal-bq** [comment]
@vincent2mots Disabling hostname verification isn't working on Windows and the driver doesn't provide a way to specify the certificate so check if you are able to send a curl request from [Verify the install](https://opendistro.github.io/for-elasticsearch-docs/docs/install/windows/#verify-the-install) without `--insecure`.

Alternatively, you can use Postman to send request but make sure **File** > **Settings** > **General** > **SSL ceritificate verification** is ON and **File** > **Settings** > **Certificates** doesn't have any certificate.

This will replicate the request which driver is sending to the SQL plugin.

**Comment by vincent2mots** [comment]
I will try this tomorrow! I'll tell you if it works ☺️

**Comment by coderReview** [comment]
hi @rupal-bq Self Signed certificates won't work with postman even if added to windows certmgr. The only workaround I can see is disable HTTPs in Elasticsearch configuration

**Comment by coderReview** [comment]
Also, @rupal-bq  can you check this code https://github.com/aws/aws-sdk-cpp/blob/74459ca66ab5867cab19458d9e70a7f6ced7f2ad/aws-cpp-sdk-core/source/http/windows/WinHttpSyncHttpClient.cpp#L160
Seems verification can be turned off. Don't know how to test it though.

**Comment by rupal-bq** [comment]
@coderReview Thanks for finding this. I can probably test this with an independent program that uses the AWS SDK.

**Comment by coderReview** [comment]
@rupal-bq any update? Also can we re-open the issue. thank you.

**Comment by rupal-bq** [comment]
@coderReview Sorry for the late response. `verifySSL` wasn't working with the independent test, it was returning response code `REQUEST_NOT_MADE`.

The alternative fix will be [Overriding HTTP Client](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/overriding-http-client.html) and use curl instead of WinHTTP.

Please raise an issue on the new repository [here](https://github.com/opendistro-for-elasticsearch/sql/tree/master/sql-odbc)

**Comment by coderReview** [comment]
Done. https://github.com/opendistro-for-elasticsearch/sql/issues/686

**Comment by coderReview** [comment]
if you can help me setting up the build environment I can help taking a look at this.

**Comment by rupal-bq** [comment]
@coderReview Sure. That will be great. 

All you need to do for setting up a build environment is 
- add [dependencies](https://github.com/opendistro-for-elasticsearch/sql/blob/develop/sql-odbc/BUILD_INSTRUCTIONS.md#windows-dependencies)
- get source code
- run script `build_win_<debug/release><32/64>.ps1` from `Developer PowerShell for VS`. After this you can open `global_make_list.sln` in Visual Studio.
- set dsn & dataset for [running tests](https://github.com/opendistro-for-elasticsearch/sql/blob/develop/sql-odbc/BUILD_INSTRUCTIONS.md#running-tests)

Check [Build Instructions](https://github.com/opendistro-for-elasticsearch/sql/blob/develop/sql-odbc/BUILD_INSTRUCTIONS.md) for more details.

Let me know if you have any questions.
