### ISSUE TITLE
mac-installer 1.7 failure

### ISSUE THREAD

**Issue by nikersason** [opendistro-for-elasticsearch/sql-odbc#97]
Are there any known problems with mac-installer v1.7.0.0? 

My installation attempt on MacOS Catalina v10.15.4 fails, and I'm seeing the following in logs:
installd[1725]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.u8xo7K/Scripts/com.Amazon.ODFE SQL ODBC Driver.Driver.7qOYqn
installd[1725]: ./postinstall: dyld: Library not loaded: @rpath/libodfesqlodbc.dylib
installd[1725]: ./postinstall:   Referenced from: /usr/local/lib/odfe-sql-odbc/bin/dsn_installer
installd[1725]: ./postinstall:   Reason: image not found
installd[1725]: ./postinstall: /tmp/PKInstallSandbox.u8xo7K/Scripts/com.Amazon.ODFE SQL ODBC Driver.Driver.7qOYqn/postinstall: line 14: 27143 Abort trap: 6           ${FINAL_INSTALL_DIR}/bin/dsn_installer ${FINAL_INSTALL_DIR}/bin/ > /tmp/dsn_installer.log

...
Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “ODFE SQL ODBC Driver-0.2.0-Darwin.pkg”

**Comment by abbashus** [comment]
@nikersason  Where are you getting the installer from? The installer version looks off `ODFE SQL ODBC Driver-0.2.0-Darwin.pkg`, it should be `ODFE SQL ODBC Driver-1.7.0.0-Darwin.pkg`.

**Comment by nikersason** [comment]
Hi @abbashus , I'm getting it from https://github.com/opendistro-for-elasticsearch/sql-odbc/releases/tag/v1.7.0.0.

**Comment by abbashus** [comment]
@nikersason Let me fix it.

**Comment by jordanw-bq** [comment]
@nikersason Note: before re-installing the driver, make sure to remove the driver's install directory (`/usr/local/lib/odfesqlodbc`)

**Comment by nikersason** [comment]
@abbashus @jordanw-bq The new installer was successful. I am unfortunately having problems testing it because iODBC Administrator crashes every time I try to add a DSN. 

The iODBC documentation does not list MacOS Catalina as supported (http://www.iodbc.org/dataspace/doc/iodbc/wiki/iodbcWiki/Downloads), however it's listed as supported for this Driver. Have you been able to successfully configure this using iODBC Administrator? Any version considerations or other advice? Thanks again for your help.

**Comment by jordanw-bq** [comment]
@nikersason Glad to hear the new installer worked!
In order to configure a DSN on Catalina, you will need to run iODBC Administrator using `sudo`:
`sudo /Applications/iODBC/iODBC\ Administrator64.app/Contents/MacOS/iODBC\ Administrator64`

We have more information at this section of our README:
https://github.com/opendistro-for-elasticsearch/sql-odbc#mac

**Comment by nikersason** [comment]
@jordanw-bq  - I had been running Administrator using sudo. I tried installing another ODBC Manager and through that was able to configure the DSN. I'm having connection issues now, but that relates to issue #94 so I will comment there. Thank you!
